#!/bin/sh
#
# Set all files in /app to 201401010000 datetime. This will help with
# docker caching.

/usr/bin/git $@
if [ -d "/app" ]; then
  echo ".git" >> /app/.dockerignore 
  find /app | xargs touch -t 201401010000.00
fi
